### PR TITLE
[fix] avoid `read: -p: no coprocess`

### LINKED ISSUE #25: [BUG] read: -p: no coprocess
When I run the command ```curl -s -L https://raw.githubusercontent.com/SaphireVert/docker-minecraft/master/install.sh | bash -s```, there is this error : ```read: -p: no coprocess```

### PR DESCRIPTION
**Pull request by ponsfrilus**
This fixes #25

### CODE REVIEW

File: install.sh [hunk 1]
```diff
@@ -62,7 +62,8 @@ function ensure_dotenv_present {
 }
 
 function set_the_motd {
-  read -p "Please enter the MOTD of the server [Default: A minecraft server]:" motd
+  echo -n "Please enter the MOTD of the server [Default: A minecraft server]:"
+  read motd
```
Comment (SaphireVert) [inline install.sh:66]: Interesting to know, I wil remember it !
